export const mockHeader = {
  name: { name: "姓名" },
  sex: { name: "性别" },
  idCard: {
    name: "身份证号",
    wch: 30,
  },
  birthday: {
    name: "出生日期",
    wch: 15,
  },
  primaryContactPhone: {
    name: "电话号码",
    wch: 10,
  },
  school: "就读学校",
  grade: "年级",
  address: {
    name: "地址",
    wpx: 160,
  },
  remark: {
    name: "备注",
    wpx: 240,
  },
  courseStr: {
    name: "报读课程",
    wpx: 120,
    // font: { color: { rgb: "ffff0000" } },
  },
  classStr: {
    name: "班级",
    wpx: 120,
    // font: { color: { rgb: "ffff0000" } },
  },
};

export const mockData = [
  {
    name: "Devin",
    sex: "female",
    idCard: 4419001999999,
    birthday: "1999-01-01",
    primaryContactPhone: 1379877777,
    primaryContactName: "HALI",
    relation: "Father",
    nickName: "N",
    school: "DZY",
    grade: 3,
    address: "thui street",
    remark: "gun",
    courses: [{ name: "英语" }],
    classes: [{ name: "A" }],
  },
  {
    name: "Devin",
    sex: "female",
    idCard: 4419001999999,
    birthday: "1999-01-01",
    primaryContactPhone: 137985555,
    primaryContactName: "HALI",
    relation: "Father",
    nickName: "N",
    school: "DZY",
    grade: 3,
    address: "thui street",
    remark: "gun",
    courses: [{ name: "英语" }],
    classes: [{ name: "A" }],
  },
  {
    name: "Devin",
    sex: "female",
    idCard: 4419001999999,
    birthday: "1999-01-01",
    primaryContactPhone: 137980000,
    primaryContactName: "HALI",
    relation: "Father",
    nickName: "N",
    school: "DZY",
    grade: 3,
    address: "thui street",
    remark: "gun",
    courses: [{ name: "英语" }],
    classes: [{ name: "A" }],
  },
  {
    name: "LEO",
    sex: "male",
    idCard: 441900112121299,
    birthday: "1999-02-01",
    primaryContactPhone: 137986666,
    primaryContactName: "HALIA",
    relation: "Father",
    nickName: "1N",
    school: "HHY",
    grade: 1,
    address: "000 street",
    remark: "AI",
    courses: [{ name: "数学" }],
    classes: [{ name: "B" }],
  },
  {
    name: "LEO",
    sex: "male",
    idCard: 441900112121299,
    birthday: "1999-02-01",
    primaryContactPhone: 137980000,
    primaryContactName: "HALIA",
    relation: "Father",
    nickName: "1N",
    school: "HHY",
    grade: 1,
    address: "000 street",
    remark: "AI",
    courses: [{ name: "数学" }],
    classes: [{ name: "B" }],
  },
  {
    name: "JIN-MA",
    grade: 5,
    idCard: 441900112121200,
    address: "LUO HU",
    remark: "MANAGE",
    courses: [{ name: "需求" }],
    classes: [{ name: "B" }],
  },
  {
    name: "JIN-MA",
    grade: 5,
    idCard: 441900112121200,
    address: "LUO HU",
    remark: "MANAGE",
    courses: [{ name: "需求" }],
    classes: [{ name: "B" }],
  },
  {
    name: "ABBEN",
    grade: 5,
    idCard: 441900112121210,
    address: "FU HU",
    remark: "MANAGE",
    courses: [{ name: "需求" }],
    classes: [{ name: "B" }],
  },
];
